services:
  # Serviço 1: Seu banco de dados PostgreSQL
  postgres-db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=saldodb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Serviço 2: Sua API .NET 8 com Hot Reload
  saldozen-api:
    container_name: saldozen-container
    build:
      context: .
      dockerfile: Dockerfile
      # --- INÍCIO DA CORREÇÃO ---
      # Informa ao Docker Compose para usar o estágio 'build' do Dockerfile,
      # que contém o .NET SDK necessário para o 'dotnet watch'.
      target: build
      # --- FIM DA CORREÇÃO ---
    ports:
      - "5000:8080"
    depends_on:
      - postgres-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=saldodb;Username=postgres;Password=mysecretpassword
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - .:/src
    working_dir: /src
    command: dotnet watch run --project SaldoZen/SaldoZen.csproj --urls "http://*:8080"

volumes:
  postgres-data:

